#!/bin/bash
# encoding: UTF-8, break: linux, indent: 4 spaces, lang: bash 3+/eng
description="./$0 -h | [args...]
Bootstrap configuration managed by yadm

date: Thu Dec  5 13:00:06 CET 2019
author: confus <con-f-use@gmx.net"

libfile="$HOME/.config/yadmdotfiles/bash/jcgb.bash"
[ -r "$libfile" ] &&
    source "$libfile" ||
    { 2>echo "Requires '$libfile'!"; exit 1; }

vim_me() {
    ../yadmdotifiles/bin/nviminstall.sh || true
    if command -v nvim >/dev/null 2>&1; then
        echo "Bootstraping Vim"
        vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
    fi
}

main() {
    echo -e "Bootstrap $(date)\n========="
}

if [ "$0" = "$BASH_SOURCE" ]; then
    usage "$@"
    main "$@"
fi
