#!/usr/bin/env bash
# encoding: UTF-8, break: linux, indent: 4 spaces, lang: bash 3+/eng
description="./$0 -h | [args...]
Bootstrap configuration managed by yadm

date: Thu Dec  5 13:00:06 CET 2019
author: confus <con-f-use@gmx.net"

libfile="$HOME/.config/yadmdotfiles/bash/jcgb.bash"
[ -r "$libfile" ] &&
    source "$libfile" ||
    { 2>echo "Requires '$libfile'!"; exit 1; }
sudo=$(command -v sudo 2>/dev/null || echo -n "")
#yadm="$HOME/.local/bin/yadm"
yadm="yadm"

main() {
    echo -e "Bootstrap $(date)\n========="
    $sudo chown -R "$USER" "$HOME/.config/yadmdotfiles"
    yadm_submods
    install_debs
    mkdir -p ~/.cache/vlc
    chmod g+rw ~/.cache/vlc
    if command -v gnome-keyring &>/dev/null; then
        $HOME/.config/yadmdotfiles/bin/git-gnome-keyring.sh
    fi
    if [ ! -z "${TMPSH:-}" ]; then
        get_tmpsh
    fi
    if [ ! -z "${NVIM:-}" ]; then
        neovim_me &> /tmp/nvime.log &
    fi
    source $HOME/.bashrc
    "$HOME/.config/yadmdotfiles/bash/bashit"
}

#-------------

install_debs(){
    if command -v apt-get &>/dev/null; then
        $sudo apt-get update
        $sudo apt-get install \
            pass curl htop dpkg screen net-tools \
            tar unzip p7zip-full
    fi
}


get_tmpsh() {
    git clone --recursive \
      'https://conserve.dynu.net/gitlab/jan/pass.git' \
      ~/.config/password-store || true
    echo 'tV5|Htm|ek'
    oldpwd=$(pwd)
    cd $(mktemp -d)
    curl -L "https://confus:$(systemd-ask-password unithi0)@unethische.org/misc/ident/keys.gpg" -o "keys.gpg"
    file keys.gpg | grep -q "encrypted data"
    gpg -d --batch --passphrase "$(systemd-ask-password smspw)" keys.gpg > keys.tgz
    tar xvf keys.tgz
    gpg --import keys/* 
    echo trust 5
    gpg --edit-key EEF19B71F9C734D8
    rm -rf keys keys.tgz keys.gpg
    cd "$oldpwd"
}


neovim_me() {
    $HOME/.config/yadmdotifiles/bin/nviminstall.sh || true
    if command -v nvim >/dev/null 2>&1; then
        echo "Bootstraping Vim"
        nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
    fi
}


yadm_submods() {
    oldpwd="$(pwd)"
    cd "$HOME"
    $yadm submodule update --recursive --init
    # yadm remote set-url origin "git@github.com:con-f-use/yadmdotfiles.git"
    #$yadm remote set-url gitlab "git@conserve.dynu.net:29222/jan/yadmdotfiles.git"
    $yadm remote add gitlab "git@conserve.dynu.net:29222/jan/yadmdotfiles.git" || true
    echo "don't forget to bashitall"
    cd "$oldpwd"
}


if [ "$0" = "$BASH_SOURCE" ]; then
    usage "$@"
    main "$@"
fi
