#!/bin/bash

#############
# General
#############
#shopt -s autocd        # cd into directories without typing "cd"
shopt -s cdspell        # Correct small errors in `cd`
shopt -s checkwinsize   # Update terminal size
shopt -s checkhash      # Check if hashed commands exist before running
shopt -s dotglob        # Include files with leading dots in pattern matching
shopt -s extglob        # Enable extended globbing: !(foo), ?(bar|baz)...
# shopt -u hostcomplete # Don't assume a word with a @ in it is a hostname
shopt -s no_empty_cmd_completion  # Don't complete empty lines
shopt -s progcomp       # Use programmable completion, if available
shopt -s shift_verbose  # Warn when shifting nonexistent values off an array
shopt -u sourcepath     # No path-search for `source` builtin
for option in autocd globstar dirspell direxpand direxpand; do
    if ((BASH_VERSINFO[0] >= 4)); then
        shopt -s "$option"
    fi
done
export PATH="$HOME/bin:$HOME/.local/bin:$(readlink -f "$BASHYDM/../bin"):$PATH"
if [ ! -x "$EDITOR" ]; then
    export EDITOR=/usr/bin/vim
fi
shopt -u mailwarn       # Don't tell me when my mail is read
unset MAILCHECK

#############
# History
#############
shopt -s histappend
shopt -s cmdhist      # Multi-line commands --> one history entry
shopt -s histreedit   # If history expansion fails, reload the command
shopt -s histverify   # Load history expansion as the next command
#shopt -s lithist      # Don't change newlines to semicolons in history
export HISTIGNORE='ignoreboth:ls:[bf]g:exit:pwd:clear:history'  # don't include trivial stuff in command history
export HISTSIZE=10000000
export HISTFILESIZE="Unlimited"
export HISTFILE="$HOME/.config/yadmdotfiles/bash/history"
export HISTTIMEFORMAT='%F %T ' # human readable history format
grep -q 'hisotry -a' <<< $PROMPT_COMMAND || export PROMPT_COMMAND="${PROMPT_COMMAND}; history -a"
export PROMPT_COMMAND=$(sed 's/;\(\s\|;\)\+/;/g' <<< $PROMPT_COMMAND | sed 's/;*$//g' | sed 's/^;*//g')


##############
# Python
##############
export PYTHONIOENCODING='UTF-8';
[ -r "$HOME/.pycustom" ] &&
    export PYTHONSTARTUP="$HOME/.pycustom"

#############
# Misc
#############
export MAKEFLAGS="-j $(nproc)"

# For VMWare Remote Console (vmrc) to fix Segfaulting "Fail to load executable. Exiting.
export VMWARE_USE_SHIPPED_LIBS=force
xset r rate 300 50
